Homework 7 completed
alxrusinov/otus_golang pull request #8
Opened 2023-01-09 11:03 UTC by alxrusinov

## Домашнее задание №7 «Утилита для копирования файлов»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-01-09 11:28 UTC, dshemin requested changes

2023-01-09 11:28 UTC, dshemin commented on hw07_file_copying/copy.go
> +	fromFile, fromError := os.Open(fromPath)
Совет:

Нет острой необходимости давать ошибке имя отличное от `err`. Это только запутывает.

2023-01-09 11:28 UTC, dshemin commented on hw07_file_copying/copy.go
> +	info, errStat := fromFile.Stat()
Совет:

Не стоит давать имя ошибке отличное от `err` если мы эту ошибку тут же обрабатываем. Только усложняет чтение кода.

2023-01-09 11:28 UTC, dshemin commented on hw07_file_copying/copy.go
> +	readingLimit := limit
Совет:

Стоит передвинуть данную переменную вниз. К тому месту где мы начинаем её использовать.

2023-01-09 11:28 UTC, dshemin commented on hw07_file_copying/copy.go
> +	buf := make([]byte, readingLimit)
Критично:

А что если у нас файл размером 100 гигабайт? Мы будем пытаться его весь вычитать в память?

2023-01-09 11:28 UTC, dshemin commented on hw07_file_copying/go.mod
>  module github.com/fixme_my_friend/hw07_file_copying
Критично:

Не go gettable.

2023-01-09 11:28 UTC, dshemin commented on hw07_file_copying/copy.go
> +	fromFile, toFile, err := prepareFiles(fromPath, toPath)
Важно:

А что будет если у нас `fromPath` и `toPath` равны?

2023-01-09 19:36 UTC, alxrusinov commented on hw07_file_copying/go.mod
>  module github.com/fixme_my_friend/hw07_file_copying
здесь не понимаю. Команда go get github.com/cheggaaa/pb/v3 и  go mod tidy отработали

2023-01-10 03:49 UTC, dshemin approved these changes

2023-01-10 03:49 UTC, dshemin commented on hw07_file_copying/copy.go
> +	_, err = io.CopyN(toFile, barReader, readingLimit)
Совет:

Можно упростить до:
```
_, err = io.CopyN(...)
return err
```

2023-01-10 16:58 UTC, merged